### ISSUE TITLE
ImportError: libpcl_keypoints.so.1.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by CogmanCVN** [csiro-robotics/locus#3]
Hello, when I configure the environment according to the suggestions in readme and run the code, an error occurs:

/home/zqy/LIBRARY/anaconda3/envs/locus_env/bin/python3.6 /home/zqy/PycharmProjects/locus-main/main.py
Traceback (most recent call last):
  File "/home/zqy/PycharmProjects/locus-main/main.py", line 18, in <module>
    from segmentation.extract_segments import *
  File "/home/zqy/PycharmProjects/locus-main/segmentation/extract_segments.py", line 4, in <module>
    import pcl
  File "/home/zqy/.local/lib/python3.6/site-packages/pcl/__init__.py", line 2, in <module>
    from ._pcl import *
ImportError: libpcl_keypoints.so.1.7: cannot open shared object file: No such file or directory

Why rely on this file: **libpcl_ keypoints.so.1.7_**？？？

My system is Ubuntu 18.04. I have installed:
tensorflow1.13.1
pcl-1.8.1
open3d-0.11.2

I hope you can give me some guidance

**Comment by kavisha725** [comment]
Hi, 
This is probably from `pcl` and `python-pcl` not being installed properly. 
Did you follow the instructions in: `utils/setup_python_pcl.txt` ?
